<?php

namespace App\Services;

class StreamerService
{
    /**
     * Get all streamers (usernames only)
     */
    public function getStreamers(): array
    {
        $detailed = $this->getStreamersWithDetails();
        return array_column($detailed, 'kickUsername');
    }

    /**
     * Get detailed streamer information
     */
    public function getDetailedStreamers(): array
    {
        return $this->getStreamersWithDetails();
    }
 
    /**
     * Get streamers with details
     */
    public function getStreamersWithDetails(): array
    {
        return [
            [
                'id' => 1,
                'name' => 'Kuku',
                'kickUsername' => 'kukudota2',
                'nameIcon' => '',
                'tags' => ['GodFather of PH Dota 2', 'Professional Dota 2 Player', 'Position 5 | Hard Support', 'Top 7 TI', 'WESG Champion'],
                'description' => 'Veteran Filipino Dota 2 captain known for elite leadership, strong shot-calling, and international success.',
                'followers' => 69000,
                'kickLink' => 'https://kick.com/kukudota2',
                'websiteLink' => 'https://www.kukudota2.com/',
                'facebookLink' => 'https://www.facebook.com/gaming/KukuDota.Official',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/kuku.jpg'
            ],
            [
                'id' => 2,
                'name' => 'Gabbi',
                'nameIcon' => '',
                'kickUsername' => 'gabbidoto',
                'tags' => ['Professional Dota 2 Player', 'Position 1 | Carry', 'Major Champion', 'TI Player', 'WESG Champion'],
                'description' => 'Filipino Dota 2 core player known for explosive teamfight impact and international success.',
                'followers' => 80800,
                'kickLink' => 'https://kick.com/gabbidoto',
                'websiteLink' => 'https://www.gabbidoto.com/',
                'facebookLink' => 'https://www.facebook.com/Gabbidoto',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/gabbi.jpg'
            ],
            [
                'id' => 3,
                'name' => 'Armel',
                'nameIcon' => '',
                'kickUsername' => 'armeldoto',
                'tags' => ['Professional Dota 2 Player', 'Position 2 | Midlaner', 'Major Champion', 'TI Player', 'WESG Champion'],
                'description' => 'Filipino Dota 2 mid player known for high-level mechanics and international success.',
                'followers' => 66600,
                'kickLink' => 'https://kick.com/armeldoto',
                'websiteLink' => 'https://armeldota.com/',
                'facebookLink' => 'https://www.facebook.com/armeldoto/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/armel.png'
            ],
            [
                'id' => 4,
                'name' => 'DJ',
                'nameIcon' => '',
                'kickUsername' => 'djdoto',
                'tags' => ['Professional Dota 2 Player', 'Position 4 | Soft Support', 'Top 4 TI'],
                'description' => 'Veteran Filipino Dota 2 support known for clutch saves, high game sense, and international success.',
                'followers' => 33900,
                'kickLink' => 'https://kick.com/djdoto',
                'websiteLink' => 'https://djdota.com/',
                'facebookLink' => 'https://www.facebook.com/djdoto',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/dj.jpg'
            ],
            [
                'id' => 5,
                'name' => 'Yowe',
                'nameIcon' => '',
                'kickUsername' => 'yowe',
                'tags' => ['Professional Dota 2 Player', 'Position 2 | Midlaner', 'Chosen Bai'],
                'description' => 'Filipino Dota 2 midlaner recognized for fearless plays and game-changing impact in high-level matches.',
                'followers' => 61000,
                'kickLink' => 'https://kick.com/yowe',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/yoweDotes',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/yowe.jpg'
            ],
            [
                'id' => 6,
                'name' => 'Palos',
                'kickUsername' => 'solapsapdota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 1 | Carry', 'Riyadh Player'],
                'description' => 'Filipino Dota 2 carry known for sharp mechanics, aggressive plays, and international experience.',
                'followers' => 36100,
                'kickLink' => 'https://kick.com/solapsapdota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/PalosDota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/palos.jpg'
            ],
            [
                'id' => 7,
                'name' => 'Kokz',
                'kickUsername' => 'kokzdota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 3 | Offlane'],
                'description' => 'Filipino Dota 2 rising star recognized for game-changing impact.',
                'followers' => 39400,
                'kickLink' => 'https://kick.com/kokzdota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/Kokzdoto/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/kokz.png'
            ],
            [
                'id' => 8,
                'name' => 'Abat',
                'kickUsername' => 'abatdota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 1 | Carry', 'Dota 2 Caster'],
                'description' => 'Filipino Dota 2 rising star recognized for aggressive plays and clutch impact.',
                'followers' => 41600,
                'kickLink' => 'https://kick.com/abatdota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/Abatdota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/abat.png'
            ],
            [
                'id' => 9,
                'name' => 'Jwl',
                'kickUsername' => 'jwldota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 5 | Hard Support'],
                'description' => 'Filipino Dota 2 rising star recognized for skillful plays and versatile support roles.',
                'followers' => 28600,
                'kickLink' => 'https://kick.com/jwldota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/jwldota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jwl.jpg'
            ],
            [
                'id' => 10,
                'name' => 'Tino',
                'kickUsername' => 'tinodota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 3 | Offlane', 'Riyadh Player'],
                'description' => 'Filipino Dota 2 offlane player known for strong teamfight presence and consistent competitive impact.',
                'followers' => 15500,
                'kickLink' => 'https://kick.com/tinodota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/dota2tino',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/tino.jpg'
            ],
            [
                'id' => 11,
                'name' => 'Karl',
                'kickUsername' => 'karldotaa',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 2 | Midlaner', 'TI Player', 'ESL One Champion'],
                'description' => 'Filipino Dota 2 midlaner known for sharp mechanics, consistent performance, and international experience.',
                'followers' => 39100,
                'kickLink' => 'https://kick.com/karldotaa',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/KarlDota.Official',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/karl.jpg'
            ],
            [
                'id' => 12,
                'name' => 'JG',
                'kickUsername' => 'jgdota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 3 | Offlaner'],
                'description' => 'Filipino Dota 2 offlaner known for skillful plays and competitive exposure.',
                'followers' => 18500,
                'kickLink' => 'https://kick.com/jgdota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/JGdota2',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jg.png'
            ],
            [
                'id' => 13,
                'name' => 'Sep',
                'kickUsername' => 'sepdoto',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 4 | Soft Support'],
                'description' => 'Filipino Dota 2 soft support known for skillful plays and impactful teamfight presence.',
                'followers' => 20000,
                'kickLink' => 'https://kick.com/sepdoto',
                'websiteLink' => 'https://www.sepdoto.com/',
                'facebookLink' => 'https://www.facebook.com/sepdoto',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/sep.png'
            ],
            [
                'id' => 14,
                'name' => 'Lewis',
                'kickUsername' => 'lewisdotaa',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 2 | Midlaner'],
                'description' => 'Filipino Dota 2 midlaner known for sharp mechanics and consistent performance.',
                'followers' => 11100,
                'kickLink' => 'https://kick.com/lewisdotaa',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/profile.php?id=61578067661034',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/lewis.jpg'
            ],
            [
                'id' => 15,
                'name' => 'Natsumi',
                'kickUsername' => 'natsumidota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Riyadh Player', 'Carry for OG'],
                'description' => 'Filipino Dota 2 carry known for sharp mechanics, strategic farming, and international experience.',
                'followers' => 33600,
                'kickLink' => 'https://kick.com/natsumidota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/natsumidota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/natsumi.jpg'
            ],
            [
                'id' => 16,
                'name' => 'Nikko',
                'kickUsername' => 'nikkodota2',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Riyadh Player', 'Offlane for OG'],
                'description' => 'Filipino Dota 2 offlaner recognized for impactful teamfight presence and international experience.',
                'followers' => 24200,
                'kickLink' => 'https://kick.com/nikkodota2',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/NikkoForce/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/nikko.jpg'
            ],
            [
                'id' => 17,
                'name' => 'Skem',
                'kickUsername' => 'skemdota123',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'TI Player', 'Riyadh Player', 'Hard Support for OG'],
                'description' => 'Filipino Dota 2 support known for smart plays, solid vision control, and international experience.',
                'followers' => 14700,
                'kickLink' => 'https://kick.com/skemdota123',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/skemdota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/skem.jpg'
            ],
            [
                'id' => 18,
                'name' => 'Tims',
                'kickUsername' => 'timsdota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Major Champion', 'Top 7 TI', 'WESG Champion', 'Soft Support for OG'],
                'description' => 'Filipino Dota 2 mid player known for high-level mechanics and international success.',
                'followers' => 27200,
                'kickLink' => 'https://kick.com/timsdota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/timsdotaofficial',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/tims.png'
            ],
            [
                'id' => 19,
                'name' => 'Jaunuel',
                'kickUsername' => 'jaunueldota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 5 | Hard Support', 'TI Player', 'Riyadh Player'],
                'description' => 'Filipino Dota 2 support known for smart positioning, strong game sense, and international competition.',
                'followers' => 29000,
                'kickLink' => 'https://kick.com/jaunueldota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/JaunuelGaming/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jaunuel.png'
            ],
            [
                'id' => 20,
                'name' => 'Jing',
                'kickUsername' => 'jingdota',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player', 'Position 5 | Hard Support', 'TI Player'],
                'description' => 'Filipino Dota 2 rising star support known for adaptability, and impactful performances.',
                'followers' => 22700,
                'kickLink' => 'https://kick.com/jingdota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/p/Jingdota-100082864195706/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jing.jpg'
            ],
            [
                'id' => 21,
                'name' => 'JtzCast',
                'kickUsername' => 'jtzcast',
                'nameIcon' => '',
                'tags' => ['Professional Caster', 'Dota 2 Streamer', 'Ex Manager of Team Kukuys v1', 'Kick Streamer'],
                'description' => 'Filipino Dota 2 caster known for insightful live commentary, and engaging audience interaction.',
                'followers' => 18400,
                'kickLink' => 'https://kick.com/jtzcast',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/Jettezee/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jtz.jpg'
            ],
            [
                'id' => 22,
                'name' => 'Nevertheless',
                'kickUsername' => 'nevertheless',
                'nameIcon' => '',
                'tags' => ['Manager of Team Kukuys v2', 'Dota 2 Streamer', 'Kick Streamer'],
                'description' => 'Content creator known for live commentary, and supporting Team Tekla\'s competitive journey.',
                'followers' => 19100,
                'kickLink' => 'https://kick.com/nevertheless',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/neverthelessdota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/kyle.jpg'
            ],
            [
                'id' => 23,
                'name' => 'LashSegway28',
                'kickUsername' => 'lashsegway28',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Dota 2 Streamer', 'Dota 2 Caster'],
                'description' => 'Content creator known for live commentary and variety gameplays.',
                'followers' => 18600,
                'kickLink' => 'https://kick.com/lashsegway28',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/Lashsegway28/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/lash.jpg'
            ],
            [
                'id' => 24,
                'name' => 'JaboleroDota',
                'kickUsername' => 'jabolerodota',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Dota 2 Streamer', 'IRL Streamer'],
                'description' => 'Content creator known for Dota 2 Streamer and IRL Streamer.',
                'followers' => 12100,
                'kickLink' => 'https://kick.com/jabolerodota',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/Jabolerodota/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jabolero.jpg?v=1'
            ],
            [
                'id' => 26,
                'name' => 'Chupaeng',
                'kickUsername' => 'chupaeng',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer', 'GTA RP Streamer'],
                'description' => 'Content creator known for GTA RP Streamer, variety gameplays, and engaging streams',
                'followers' => 15300,
                'kickLink' => 'https://kick.com/chupaeng',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/p/Chupaeng-100092376301513/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/chupaeng.jpg'
            ],
            [
                'id' => 27,
                'name' => 'SunshineMelodyyy',
                'kickUsername' => 'sunshinemelodyyy',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer', 'GTA RP Streamer'],
                'description' => 'Content creator known for GTA RP Streamer, variety gameplays, and engaging streams',
                'followers' => 18000,
                'kickLink' => 'https://kick.com/sunshinemelodyyy',
                'websiteLink' => 'https://sunshinemelody.com/',
                'facebookLink' => 'https://www.facebook.com/ItsJoannaGaming/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/sunshine.jpg'
            ],
            [
                'id' => 28,
                'name' => 'Jawocolet',
                'kickUsername' => 'jawocolet',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer'],
                'description' => 'Content creator known for variety gameplays, and engaging streams',
                'followers' => 4700,
                'kickLink' => 'https://kick.com/jawocolet',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/jawocolet/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/jawo.jpg'
            ],
            [
                'id' => 35,
                'name' => 'Eyyou',
                'kickUsername' => 'eyyou',
                'nameIcon' => '',
                'tags' => ['Professional Dota 2 Player','Top 7 TI', 'WESG Champion'],
                'description' => 'Filipino Dota 2 support known for solid vision control, and international experience.',
                'followers' => 15600,
                'kickLink' => 'https://kick.com/eyyou',
                'websiteLink' => '',
                'facebookLink' => '',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/eyyou.jpg'
            ],
            [
                'id' => 29,
                'name' => 'Joevy',
                'kickUsername' => 'joevydota2',
                'nameIcon' => '',
                'tags' => ['Dota 2 Streamer', 'Manager of Xctn'],
                'description' => 'Dota 2 streamer and manager of Xctn, supporting Xctn competitive journey.',
                'followers' => 11100,
                'kickLink' => 'https://kick.com/joevydota2',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/physicsjoevy/',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/joevy.png'
            ],
            [
                'id' => 30,
                'name' => 'RexhaScarlett',
                'kickUsername' => 'rexhascarlett',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer'],
                'description' => 'Content creator known for variety gameplays, engaging streams, and community-driven content.',
                'followers' => 5800,
                'kickLink' => 'https://kick.com/rexhascarlett',
                'websiteLink' => '',
                'facebookLink' => '',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/rexha.png'
            ],
            [
                'id' => 32,
                'name' => 'Moodyemel',
                'kickUsername' => 'moodyemel',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer'],
                'description' => 'Content creator known for variety gameplays, engaging streams, and community-driven content.',
                'followers' => 4100,
                'kickLink' => 'https://kick.com/moodyemel',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/Bananabreiva',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/moodyemel.png'
            ],
            [
                'id' => 33,
                'name' => 'Aerein',
                'kickUsername' => 'aerein',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer'],
                'description' => 'Content creator known for variety gameplays, engaging streams, and community-driven content.',
                'followers' => 7400,
                'kickLink' => 'https://kick.com/aerein',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/elainecuares',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/ela.png'
            ],
            [
                'id' => 34,
                'name' => 'PeachyBunny',
                'kickUsername' => 'peachybunny',
                'nameIcon' => '',
                'tags' => ['Kick Streamer', 'Variety Streamer'],
                'description' => 'Content creator known for variety gameplays, engaging streams, and community-driven content.',
                'followers' => 7900,
                'kickLink' => 'https://kick.com/peachybunny',
                'websiteLink' => '',
                'facebookLink' => '',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/peachy.png'
            ],
            [
                'id' => 36,
                'name' => 'Rainzerlyn',
                'kickUsername' => 'rainzerlyn',
                'nameIcon' => '',
                'tags' => ['Professional Caster', 'Kick Streamer', 'Variety Streamer'],
                'description' => 'Content creator known for shoutcasting, engaging streams, and community-driven content.',
                'followers' => 13600,
                'kickLink' => 'https://kick.com/rainzerlyn',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/statsgirlrain',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/rainzerlyn.png'
            ],
            [
                'id' => 37,
                'name' => 'Meepwet',
                'kickUsername' => 'meepwet',
                'nameIcon' => '',
                'tags' => ['Dota 2 Streamer', 'Kick Streamer', 'Variety Streamer', 'Akatsuki', 'PH Sniper'],
                'description' => 'Dota 2 streamer known for competitive gameplay, engaging streams, and community-driven content.',
                'followers' => 6700,
                'kickLink' => 'https://kick.com/meepwet',
                'websiteLink' => '',
                'facebookLink' => 'https://www.facebook.com/meepwetgaming',
                'isLive' => false,
                'icon' => 'fab fa-kickstarter',
                'image' => 'images/kukuys_streamer/meepwet.jpg'
            ]
        ];
    }
}